import { resolve } from 'node:path';
import { homedir } from 'node:os';

export interface Config {
  sourceHtmlFile: string; // The origin html file generated by build tools like vit.
  sourceJsFile: string;
  sourceCssFile: string;

  deployRootDir: string;
  deployHtmlDir: string;
  deployAssetDir: string;

  staticPrefix: string; // Used when rendering html template.
  packageDir: string; // The directory containing package.json.

  targetHtmlFile: string; // Intermediate file for html template.
  targetVersionFile: string; // A plain text file containing a string of app version.
}

